spring:
  application:
    name: cart-demo
  profiles:
    active: local
  jpa:
    open-in-view: false
    properties:
      hibernate.jdbc.batch_size: 25
  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  api-docs:
    title: Cart Demo API
    enabled: true
  swagger-ui:
    enabled: true
